// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApDkS_gQ9PU1wDcuf-jLsaM8qErJB5FlA',
    appId: '1:764491921135:web:c5bcde335acefb5ce34d1a',
    messagingSenderId: '764491921135',
    projectId: 'memowebapp-9f6e6',
    authDomain: 'memowebapp-9f6e6.firebaseapp.com',
    databaseURL: 'https://memowebapp-9f6e6-default-rtdb.firebaseio.com',
    storageBucket: 'memowebapp-9f6e6.appspot.com',
    measurementId: 'G-Y0M9E2R91D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBF_yHCQyY-q1mDj_NmZiRfuHVVBcnzD0Q',
    appId: '1:764491921135:android:065ea29a0f7c510ee34d1a',
    messagingSenderId: '764491921135',
    projectId: 'memowebapp-9f6e6',
    databaseURL: 'https://memowebapp-9f6e6-default-rtdb.firebaseio.com',
    storageBucket: 'memowebapp-9f6e6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3h8Bp9ourKMOE1nujCypaXon5n-A3WCA',
    appId: '1:764491921135:ios:ce9926c26974c6bae34d1a',
    messagingSenderId: '764491921135',
    projectId: 'memowebapp-9f6e6',
    databaseURL: 'https://memowebapp-9f6e6-default-rtdb.firebaseio.com',
    storageBucket: 'memowebapp-9f6e6.appspot.com',
    iosBundleId: 'com.example.testProj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3h8Bp9ourKMOE1nujCypaXon5n-A3WCA',
    appId: '1:764491921135:ios:0f325df180bbd43de34d1a',
    messagingSenderId: '764491921135',
    projectId: 'memowebapp-9f6e6',
    databaseURL: 'https://memowebapp-9f6e6-default-rtdb.firebaseio.com',
    storageBucket: 'memowebapp-9f6e6.appspot.com',
    iosBundleId: 'com.example.testProj.RunnerTests',
  );
}
