// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD069aAMgvQPlUDdJF7llK13z_vw2rQlbc',
    appId: '1:429802887971:web:b5624dc524d1740d208a96',
    messagingSenderId: '429802887971',
    projectId: 'word-clear',
    authDomain: 'word-clear.firebaseapp.com',
    storageBucket: 'word-clear.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhzSNPfsoKjFFyA_H4oxaUFoN-OJAfRJY',
    appId: '1:429802887971:android:525f0379c071608f208a96',
    messagingSenderId: '429802887971',
    projectId: 'word-clear',
    storageBucket: 'word-clear.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0AzvnnT1-cRx3lN7Vl59Hf2G-LJ4LBjw',
    appId: '1:429802887971:ios:cc84d79fa2f04523208a96',
    messagingSenderId: '429802887971',
    projectId: 'word-clear',
    storageBucket: 'word-clear.appspot.com',
    iosBundleId: 'com.example.testProj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0AzvnnT1-cRx3lN7Vl59Hf2G-LJ4LBjw',
    appId: '1:429802887971:ios:89f91166a9cdc48f208a96',
    messagingSenderId: '429802887971',
    projectId: 'word-clear',
    storageBucket: 'word-clear.appspot.com',
    iosBundleId: 'com.example.testProj.RunnerTests',
  );
}
